FROM maven:3.9.3-amazoncorretto-17-debian-bookworm AS builder
WORKDIR /usr/src/app
COPY . .
ENV SPRING_PROFILES_ACTIVE=staging
RUN mvn clean install -DskipTests

FROM amazoncorretto:17
WORKDIR /usr/src/app
ENV SPRING_PROFILES_ACTIVE=staging
COPY --from=builder /usr/src/app/target/workspace-0.0.1-SNAPSHOT.jar .
CMD ["java", "-jar", "workspace-0.0.1-SNAPSHOT.jar"]