ALTER TABLE application
    ALTER COLUMN "type" TYPE VARCHAR(50),
    ALTER COLUMN status TYPE VARCHAR(30),
    ALTER COLUMN approved_by TYPE VARCHAR(30),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30),
    ALTER COLUMN partner_id TYPE VARCHAR(36);

ALTER TABLE bank_account
    ALTER COLUMN bank_name TYPE VARCHAR(150),
    ALTER COLUMN bank_branch TYPE VARCHAR(100),
    ALTER COLUMN account_name TYPE VARCHAR(100),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30),
    ALTER COLUMN partner_id TYPE VARCHAR(36);

ALTER TABLE controller
    ALTER COLUMN "name" TYPE VARCHAR(100),
    ALTER COLUMN phone TYPE VARCHAR(15),
    ALTER COLUMN email TYPE VARCHAR(30),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30),
    ALTER COLUMN partner_id TYPE VARCHAR(36);

ALTER TABLE document
    ALTER COLUMN "name" TYPE VARCHAR(100),
    ALTER COLUMN file_type TYPE VARCHAR(30),
    ALTER COLUMN reference_type TYPE VARCHAR(20),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30);

ALTER TABLE menu
    ALTER COLUMN "name" TYPE VARCHAR(100),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30),
    ALTER COLUMN store_id TYPE VARCHAR(36),
    ALTER COLUMN partner_id TYPE VARCHAR(36);

ALTER TABLE notification
    ALTER COLUMN receiver TYPE VARCHAR(30),
    ALTER COLUMN subject TYPE VARCHAR(150),
    ALTER COLUMN short_description TYPE VARCHAR(150),
    ALTER COLUMN "key" TYPE VARCHAR(100);

ALTER TABLE "order"
    ALTER COLUMN status TYPE VARCHAR(20),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30),
    ALTER COLUMN store_id TYPE VARCHAR(36),
    ALTER COLUMN partner_id TYPE VARCHAR(36),
    ALTER COLUMN initial_transaction_method TYPE VARCHAR(15);

ALTER TABLE partner
    ALTER COLUMN "name" TYPE VARCHAR(150),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30),
    ALTER COLUMN logo TYPE VARCHAR(150),
    ALTER COLUMN business_code TYPE VARCHAR(20),
    ALTER COLUMN tax_code TYPE VARCHAR(20),
    ALTER COLUMN "type" TYPE VARCHAR(15);

ALTER TABLE qr_code
    ALTER COLUMN "name" TYPE VARCHAR(50),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30),
    ALTER COLUMN store_id TYPE VARCHAR(36);

ALTER TABLE representative
    ALTER COLUMN "name" TYPE VARCHAR(100),
    ALTER COLUMN identity_type TYPE VARCHAR(20),
    ALTER COLUMN identity_number TYPE VARCHAR(20),
    ALTER COLUMN phone TYPE VARCHAR(15),
    ALTER COLUMN email TYPE VARCHAR(30),
    ALTER COLUMN identity_front_image TYPE VARCHAR(150),
    ALTER COLUMN identity_back_image TYPE VARCHAR(150),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30),
    ALTER COLUMN partner_id TYPE VARCHAR(36);

ALTER TABLE store
    ALTER COLUMN "name" TYPE VARCHAR(100),
    ALTER COLUMN phone TYPE VARCHAR(15),
    ALTER COLUMN email TYPE VARCHAR(30),
    ALTER COLUMN profile_image TYPE VARCHAR(150),
    ALTER COLUMN cover_image TYPE VARCHAR(150),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30),
    ALTER COLUMN partner_id TYPE VARCHAR(36);

ALTER TABLE "user"
    ALTER COLUMN username TYPE VARCHAR(30),
    ALTER COLUMN display_name TYPE VARCHAR(100),
    ALTER COLUMN phone TYPE VARCHAR(15),
    ALTER COLUMN email TYPE VARCHAR(30),
    ALTER COLUMN avatar TYPE VARCHAR(150),
    ALTER COLUMN "type" TYPE VARCHAR(20),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30),
    ALTER COLUMN partner_id TYPE VARCHAR(36),
    ALTER COLUMN store_id TYPE VARCHAR(36);

ALTER TABLE voucher
    ALTER COLUMN discount_type TYPE VARCHAR(15),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30),
    ALTER COLUMN partner_id TYPE VARCHAR(36),
    ALTER COLUMN store_id TYPE VARCHAR(36);

ALTER TABLE voucher_order
    ALTER COLUMN description TYPE VARCHAR(100),
    ALTER COLUMN "source" TYPE VARCHAR(15),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30);

ALTER TABLE cart
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30),
    ALTER COLUMN store_id TYPE VARCHAR(36);

ALTER TABLE menu_section
    ALTER COLUMN "name" TYPE VARCHAR(100),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30);

ALTER TABLE product
    ALTER COLUMN "name" TYPE VARCHAR(100),
    ALTER COLUMN cover_image TYPE VARCHAR(150),
    ALTER COLUMN categories TYPE TEXT[],
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30),
    ALTER COLUMN partner_id TYPE VARCHAR(36),
    ALTER COLUMN store_id TYPE VARCHAR(36);

ALTER TABLE review
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30);

ALTER TABLE "transaction"
    ALTER COLUMN "method" TYPE VARCHAR(15),
    ALTER COLUMN "type" TYPE VARCHAR(15),
    ALTER COLUMN status TYPE VARCHAR(15),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30),
    ALTER COLUMN partner_id TYPE VARCHAR(36),
    ALTER COLUMN store_id TYPE VARCHAR(36);

ALTER TABLE cart_item
    ALTER COLUMN note TYPE VARCHAR(150),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30);

ALTER TABLE product_option_section
    ALTER COLUMN "name" TYPE VARCHAR(100),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30);

ALTER TABLE product_addon
    ALTER COLUMN "name" TYPE VARCHAR(50),
    ALTER COLUMN created_by TYPE VARCHAR(30),
    ALTER COLUMN updated_by TYPE VARCHAR(30);