package com.capstone.workspace.enums.notification;

public enum NotificationKey {
    HAVING_NEW_APPLICATION,
    APPROVE_CREATE_ORGANIZATION_APPLICATION_SUCCESS,
    APPROVE_CREATE_ORGANIZATION_APPLICATION_FAILED,
    HAVING_NEW_ORDER,
    ORDER_PROCESSING,
    ORDER_COMPLETED,
    ORDER_CANCELED,
    ORDER_REJECTED,
    ORDER_EXPIRED,
    REFUND_SUCCESS,
    APPLICATION_REJECTED,
    APPLICATION_SUBMITTED,
    APPLICATION_PROCESSING
}
